package descriptor

import "github.com/n8n-io/n8n-turbo/internal/engine"

func RegisterBuiltins(registry engine.Registry) {
	for _, descriptor := range Builtins() {
		registry.Register(descriptor.NodeType, NewExecutor(descriptor))
	}
}

func repoParams() []Param {
	return []Param{
		{Name: "owner", In: "path", Required: true, Type: "string"},
		{Name: "repo", In: "path", Required: true, Type: "string"},
	}
}

func sheetRangeParams() []Param {
	return []Param{
		{Name: "spreadsheetId", In: "path", Required: true, Type: "string"},
		{Name: "range", In: "path", Required: true, Type: "string", Default: "Sheet1!A:Z"},
	}
}

func airtableTableParams() []Param {
	return []Param{
		{Name: "baseId", In: "path", Required: true, Type: "string"},
		{Name: "tableId", In: "path", Required: true, Type: "string"},
	}
}

func airtableCompatTableParams() []Param {
	return []Param{
		{Name: "baseId", In: "path", Required: true, Type: "string"},
		{Name: "tableIdOrName", In: "path", Required: true, Type: "string"},
	}
}

func hubspotCursorPagination() *Pagination {
	return &Pagination{Type: "cursor", CursorParam: "after", NextPagePath: "paging.next.after", DataPath: "results", DefaultLimit: 100, LimitParam: "limit"}
}

func hubspotListParams() []Param {
	return []Param{
		{Name: "properties", In: "query", Type: "string", Default: "firstname,lastname,email,phone,company,createdate,lastmodifieddate"},
		{Name: "associations", In: "query", Type: "string"},
		{Name: "archived", In: "query", Type: "boolean", Default: false},
		{Name: "after", In: "query", Type: "string"},
		{Name: "limit", In: "query", Type: "number"},
	}
}

func stripeListPagination() *Pagination {
	return &Pagination{Type: "cursor", CursorParam: "starting_after", NextPagePath: "data.last.id", DataPath: "data", DefaultLimit: 100, LimitParam: "limit"}
}

func stripeListParams(extra ...Param) []Param {
	params := []Param{
		{Name: "limit", In: "query", Type: "number", Default: 100},
		{Name: "starting_after", In: "query", Type: "string"},
		{Name: "ending_before", In: "query", Type: "string"},
	}
	return append(params, extra...)
}

func Builtins() []Descriptor {
	return []Descriptor{
		{
			NodeType:       "n8n-nodes-base.slack",
			Name:           "slack",
			DisplayName:    "Slack",
			Version:        2,
			Description:    "Slack messaging and workspace operations",
			BaseURL:        "https://slack.com/api",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bearer"},
			CredentialType: "slackApi",
			Category:       "Communication",
			Tags:           []string{"messaging", "team", "slack"},
			ErrorCheck:     &ErrorCheck{Field: "ok", FalseIsError: true, MessageField: "error"},
			DefaultHeaders: map[string]string{
				"Content-Type": "application/json; charset=utf-8",
			},
			Operations: map[string]Operation{
				"default": {Method: "GET", Path: "/auth.test"},
				"sendMessage": {Method: "POST", Path: "/chat.postMessage", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "text", In: "body", Type: "string"},
					{Name: "blocks", In: "body", Type: "json"},
					{Name: "attachments", In: "body", Type: "json"},
					{Name: "thread_ts", In: "body", Type: "string"},
					{Name: "username", In: "body", Type: "string"},
					{Name: "icon_emoji", In: "body", Type: "string"},
					{Name: "unfurl_links", In: "body", Type: "boolean", Default: true},
				}},
				"postMessage": {Method: "POST", Path: "/chat.postMessage", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "text", In: "body", Type: "string"},
				}},
				"updateMessage": {Method: "POST", Path: "/chat.update", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "ts", In: "body", Required: true, Type: "string"},
					{Name: "text", In: "body", Type: "string"},
					{Name: "blocks", In: "body", Type: "json"},
				}},
				"deleteMessage": {Method: "POST", Path: "/chat.delete", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "ts", In: "body", Required: true, Type: "string"},
				}},
				"getPermalink": {Method: "GET", Path: "/chat.getPermalink", Params: []Param{
					{Name: "channel", In: "query", Required: true, Type: "string"},
					{Name: "message_ts", In: "query", Required: true, Type: "string"},
				}},
				"listChannels": {Method: "GET", Path: "/conversations.list", ResponseMap: "channels", Pagination: &Pagination{Type: "cursor", CursorParam: "cursor", NextPagePath: "response_metadata.next_cursor", DataPath: "channels", DefaultLimit: 200, LimitParam: "limit"}, Params: []Param{
					{Name: "types", In: "query", Type: "string", Default: "public_channel,private_channel"},
					{Name: "exclude_archived", In: "query", Type: "boolean", Default: true},
					{Name: "cursor", In: "query", Type: "string"},
					{Name: "limit", In: "query", Type: "number"},
				}},
				"getChannel": {Method: "GET", Path: "/conversations.info", ResponseMap: "channel", Params: []Param{
					{Name: "channel", In: "query", Required: true, Type: "string"},
				}},
				"createChannel": {Method: "POST", Path: "/conversations.create", BodyType: "json", ResponseMap: "channel", Params: []Param{
					{Name: "name", In: "body", Required: true, Type: "string"},
					{Name: "is_private", In: "body", Type: "boolean", Default: false},
				}},
				"inviteToChannel": {Method: "POST", Path: "/conversations.invite", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "users", In: "body", Required: true, Type: "string"},
				}},
				"listUsers": {Method: "GET", Path: "/users.list", ResponseMap: "members", Pagination: &Pagination{Type: "cursor", CursorParam: "cursor", NextPagePath: "response_metadata.next_cursor", DataPath: "members", DefaultLimit: 200, LimitParam: "limit"}, Params: []Param{
					{Name: "include_locale", In: "query", Type: "boolean", Default: false},
					{Name: "cursor", In: "query", Type: "string"},
					{Name: "limit", In: "query", Type: "number"},
				}},
				"getUser": {Method: "GET", Path: "/users.info", ResponseMap: "user", Params: []Param{
					{Name: "user", In: "query", Required: true, Type: "string"},
				}},
				"lookupUserByEmail": {Method: "GET", Path: "/users.lookupByEmail", ResponseMap: "user", Params: []Param{
					{Name: "email", In: "query", Required: true, Type: "string"},
				}},
				"addReaction": {Method: "POST", Path: "/reactions.add", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "timestamp", In: "body", Required: true, Type: "string"},
					{Name: "name", In: "body", Required: true, Type: "string"},
				}},
				"removeReaction": {Method: "POST", Path: "/reactions.remove", BodyType: "json", Params: []Param{
					{Name: "channel", In: "body", Required: true, Type: "string"},
					{Name: "timestamp", In: "body", Required: true, Type: "string"},
					{Name: "name", In: "body", Required: true, Type: "string"},
				}},
				"uploadFile": {Method: "POST", Path: "/files.uploadV2", BodyType: "multipart", ResponseMap: "file", Params: []Param{
					{Name: "channel_id", In: "body", Type: "string"},
					{Name: "filename", In: "body", Required: true, Type: "string"},
					{Name: "content", In: "body", Type: "string"},
					{Name: "binary_data", In: "body", Type: "binary"},
					{Name: "title", In: "body", Type: "string"},
					{Name: "initial_comment", In: "body", Type: "string"},
				}},
				"getChannelHistory": {Method: "GET", Path: "/conversations.history", ResponseMap: "messages", Pagination: &Pagination{Type: "cursor", CursorParam: "cursor", NextPagePath: "response_metadata.next_cursor", DataPath: "messages", DefaultLimit: 100, LimitParam: "limit"}, Params: []Param{
					{Name: "channel", In: "query", Required: true, Type: "string"},
					{Name: "oldest", In: "query", Type: "string"},
					{Name: "latest", In: "query", Type: "string"},
					{Name: "inclusive", In: "query", Type: "boolean", Default: false},
					{Name: "cursor", In: "query", Type: "string"},
					{Name: "limit", In: "query", Type: "number"},
				}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.github",
			Name:           "github",
			DisplayName:    "GitHub",
			Version:        1,
			Description:    "GitHub repositories, issues, pull requests, releases and file contents",
			BaseURL:        "https://api.github.com",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bearer"},
			CredentialType: "githubApi",
			Category:       "Development",
			DefaultHeaders: map[string]string{
				"Accept":               "application/vnd.github+json",
				"X-GitHub-Api-Version": "2022-11-28",
			},
			Operations: map[string]Operation{
				"default":       {Method: "GET", Path: "/user"},
				"getRepository": {Method: "GET", Path: "/repos/{owner}/{repo}", Params: repoParams()},
				"getRepo":       {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}", Params: repoParams()},
				"listRepos": {Method: "GET", Path: "/user/repos", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page"}, Params: []Param{
					{Name: "type", In: "query", Type: "string", Default: "all"},
					{Name: "sort", In: "query", Type: "string", Default: "updated"},
					{Name: "direction", In: "query", Type: "string", Default: "desc"},
					{Name: "page", In: "query", Type: "number"},
					{Name: "per_page", In: "query", Type: "number"},
				}},
				"createRepo": {Method: "POST", Path: "/user/repos", BodyType: "json", Params: []Param{
					{Name: "name", In: "body", Required: true, Type: "string"},
					{Name: "description", In: "body", Type: "string"},
					{Name: "private", In: "body", Type: "boolean", Default: false},
					{Name: "auto_init", In: "body", Type: "boolean", Default: false},
					{Name: "gitignore_template", In: "body", Type: "string"},
					{Name: "license_template", In: "body", Type: "string"},
				}},
				"listIssues": {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/issues", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page"}, Params: append(repoParams(),
					Param{Name: "state", In: "query", Type: "string", Default: "open"},
					Param{Name: "labels", In: "query", Type: "string"},
					Param{Name: "assignee", In: "query", Type: "string"},
					Param{Name: "since", In: "query", Type: "string"},
					Param{Name: "page", In: "query", Type: "number"},
					Param{Name: "per_page", In: "query", Type: "number"},
				)},
				"getIssue": {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/issues/{{.issue_number}}", Params: append(repoParams(), Param{Name: "issue_number", In: "path", Required: true, Type: "number"})},
				"createIssue": {Method: "POST", Path: "/repos/{owner}/{repo}/issues", BodyType: "json", Params: append(repoParams(),
					Param{Name: "title", In: "body", Required: true, Type: "string"},
					Param{Name: "body", In: "body", Type: "string"},
					Param{Name: "assignees", In: "body", Type: "json"},
					Param{Name: "labels", In: "body", Type: "json"},
					Param{Name: "milestone", In: "body", Type: "number"},
				)},
				"updateIssue": {Method: "PATCH", Path: "/repos/{{.owner}}/{{.repo}}/issues/{{.issue_number}}", BodyType: "json", Params: append(repoParams(),
					Param{Name: "issue_number", In: "path", Required: true, Type: "number"},
					Param{Name: "title", In: "body", Type: "string"},
					Param{Name: "body", In: "body", Type: "string"},
					Param{Name: "state", In: "body", Type: "string"},
					Param{Name: "labels", In: "body", Type: "json"},
					Param{Name: "assignees", In: "body", Type: "json"},
				)},
				"listPullRequests": {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/pulls", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page"}, Params: append(repoParams(),
					Param{Name: "state", In: "query", Type: "string", Default: "open"},
					Param{Name: "base", In: "query", Type: "string"},
					Param{Name: "head", In: "query", Type: "string"},
					Param{Name: "sort", In: "query", Type: "string", Default: "created"},
					Param{Name: "page", In: "query", Type: "number"},
					Param{Name: "per_page", In: "query", Type: "number"},
				)},
				"createPullRequest": {Method: "POST", Path: "/repos/{{.owner}}/{{.repo}}/pulls", BodyType: "json", Params: append(repoParams(),
					Param{Name: "title", In: "body", Required: true, Type: "string"},
					Param{Name: "body", In: "body", Type: "string"},
					Param{Name: "head", In: "body", Required: true, Type: "string"},
					Param{Name: "base", In: "body", Required: true, Type: "string"},
					Param{Name: "draft", In: "body", Type: "boolean", Default: false},
				)},
				"listReleases":   {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/releases", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page"}, Params: append(repoParams(), Param{Name: "page", In: "query", Type: "number"}, Param{Name: "per_page", In: "query", Type: "number"})},
				"createRelease":  {Method: "POST", Path: "/repos/{{.owner}}/{{.repo}}/releases", BodyType: "json", Params: append(repoParams(), Param{Name: "tag_name", In: "body", Required: true, Type: "string"}, Param{Name: "name", In: "body", Type: "string"}, Param{Name: "body", In: "body", Type: "string"}, Param{Name: "draft", In: "body", Type: "boolean", Default: false}, Param{Name: "prerelease", In: "body", Type: "boolean", Default: false}, Param{Name: "target_commitish", In: "body", Type: "string", Default: "main"})},
				"getFileContent": {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/contents/{{.path}}", Params: append(repoParams(), Param{Name: "path", In: "path", Required: true, Type: "string"}, Param{Name: "ref", In: "query", Type: "string"})},
				"createOrUpdateFile": {Method: "PUT", Path: "/repos/{{.owner}}/{{.repo}}/contents/{{.path}}", BodyType: "json", Params: append(repoParams(),
					Param{Name: "path", In: "path", Required: true, Type: "string"},
					Param{Name: "message", In: "body", Required: true, Type: "string"},
					Param{Name: "content", In: "body", Required: true, Type: "string"},
					Param{Name: "sha", In: "body", Type: "string"},
					Param{Name: "branch", In: "body", Type: "string"},
				)},
				"listBranches": {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/branches", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page"}, Params: append(repoParams(),
					Param{Name: "protected", In: "query", Type: "boolean"},
					Param{Name: "page", In: "query", Type: "number"},
					Param{Name: "per_page", In: "query", Type: "number"},
				)},
				"listCommits": {Method: "GET", Path: "/repos/{{.owner}}/{{.repo}}/commits", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page"}, Params: append(repoParams(),
					Param{Name: "sha", In: "query", Type: "string"},
					Param{Name: "path", In: "query", Type: "string"},
					Param{Name: "author", In: "query", Type: "string"},
					Param{Name: "since", In: "query", Type: "string"},
					Param{Name: "until", In: "query", Type: "string"},
					Param{Name: "page", In: "query", Type: "number"},
					Param{Name: "per_page", In: "query", Type: "number"},
				)},
				"searchIssues": {Method: "GET", Path: "/search/issues", ResponseMap: "items", Pagination: &Pagination{Type: "link", DefaultLimit: 100, LimitParam: "per_page", DataPath: "items"}, Params: []Param{
					{Name: "q", In: "query", Required: true, Type: "string"},
					{Name: "sort", In: "query", Type: "string"},
					{Name: "order", In: "query", Type: "string", Default: "desc"},
					{Name: "page", In: "query", Type: "number"},
					{Name: "per_page", In: "query", Type: "number"},
				}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.gmail",
			Name:           "gmail",
			DisplayName:    "Gmail",
			Version:        2,
			Description:    "Read, modify and send email through Gmail",
			BaseURL:        "https://gmail.googleapis.com/gmail/v1/users/me",
			AuthType:       "oauth2",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bearer", "tokenURL": "https://oauth2.googleapis.com/token", "grantType": "refreshToken"},
			CredentialType: "gmailOAuth2Api",
			Category:       "Communication",
			DefaultHeaders: map[string]string{"Accept": "application/json"},
			Operations: map[string]Operation{
				"default": {Method: "GET", Path: "/profile"},
				"listMessages": {Method: "GET", Path: "/messages", ResponseMap: "messages", Pagination: &Pagination{Type: "nextPageToken", CursorParam: "pageToken", NextPagePath: "nextPageToken", DataPath: "messages", DefaultLimit: 100, LimitParam: "maxResults"}, Params: []Param{
					{Name: "q", In: "query", Type: "string"},
					{Name: "labelIds", In: "query", Type: "string"},
					{Name: "includeSpamTrash", In: "query", Type: "boolean", Default: false},
					{Name: "pageToken", In: "query", Type: "string"},
					{Name: "maxResults", In: "query", Type: "number"},
				}},
				"getMessage": {Method: "GET", Path: "/messages/{{.messageId}}", Params: []Param{
					{Name: "messageId", In: "path", Required: true, Type: "string"},
					{Name: "format", In: "query", Type: "string", Default: "full"},
				}},
				"getAttachment": {Method: "GET", Path: "/messages/{{.messageId}}/attachments/{{.attachmentId}}", Params: []Param{
					{Name: "messageId", In: "path", Required: true, Type: "string"},
					{Name: "attachmentId", In: "path", Required: true, Type: "string"},
				}},
				"sendMessage": {Method: "POST", Path: "/messages/send", BodyType: "json", Params: []Param{
					{Name: "raw", In: "body", Type: "string"},
					{Name: "to", In: "body", Type: "string"},
					{Name: "cc", In: "body", Type: "string"},
					{Name: "bcc", In: "body", Type: "string"},
					{Name: "from", In: "body", Type: "string"},
					{Name: "replyTo", In: "body", Type: "string"},
					{Name: "subject", In: "body", Type: "string"},
					{Name: "body", In: "body", Type: "string"},
					{Name: "isHtml", In: "body", Type: "boolean", Default: false},
					{Name: "attachments", In: "body", Type: "json"},
				}},
				"deleteMessage": {Method: "POST", Path: "/messages/{{.messageId}}/trash", Params: []Param{
					{Name: "messageId", In: "path", Required: true, Type: "string"},
				}},
				"markAsRead": {Method: "POST", Path: "/messages/{{.messageId}}/modify", BodyType: "json", Params: []Param{
					{Name: "messageId", In: "path", Required: true, Type: "string"},
					{Name: "removeLabelIds", In: "body", Type: "json", Default: []any{"UNREAD"}},
				}},
				"markAsUnread": {Method: "POST", Path: "/messages/{{.messageId}}/modify", BodyType: "json", Params: []Param{
					{Name: "messageId", In: "path", Required: true, Type: "string"},
					{Name: "addLabelIds", In: "body", Type: "json", Default: []any{"UNREAD"}},
				}},
				"addLabel": {Method: "POST", Path: "/messages/{{.messageId}}/modify", BodyType: "json", Params: []Param{
					{Name: "messageId", In: "path", Required: true, Type: "string"},
					{Name: "addLabelIds", In: "body", Required: true, Type: "json"},
				}},
				"listLabels": {Method: "GET", Path: "/labels", ResponseMap: "labels"},
				"createLabel": {Method: "POST", Path: "/labels", BodyType: "json", Params: []Param{
					{Name: "name", In: "body", Required: true, Type: "string"},
					{Name: "labelListVisibility", In: "body", Type: "string", Default: "labelShow"},
					{Name: "messageListVisibility", In: "body", Type: "string", Default: "show"},
				}},
				"listDrafts": {Method: "GET", Path: "/drafts", ResponseMap: "drafts", Pagination: &Pagination{Type: "nextPageToken", CursorParam: "pageToken", NextPagePath: "nextPageToken", DataPath: "drafts", DefaultLimit: 100, LimitParam: "maxResults"}, Params: []Param{
					{Name: "pageToken", In: "query", Type: "string"},
					{Name: "maxResults", In: "query", Type: "number"},
				}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.googleSheets",
			Name:           "googleSheets",
			DisplayName:    "Google Sheets",
			Version:        4,
			Description:    "Read and write data in Google Sheets",
			BaseURL:        "https://sheets.googleapis.com/v4/spreadsheets",
			AuthType:       "oauth2",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bearer", "tokenURL": "https://oauth2.googleapis.com/token", "grantType": "refreshToken"},
			CredentialType: "googleSheetsOAuth2Api",
			Category:       "Productivity",
			Operations: map[string]Operation{
				"default": {Method: "GET", Path: "/{{.spreadsheetId}}", Params: []Param{
					{Name: "spreadsheetId", In: "path", Required: true, Type: "string"},
				}},
				"read": {Method: "GET", Path: "/{{.spreadsheetId}}/values/{{.range}}", ResponseMap: "values", Params: append(sheetRangeParams(),
					Param{Name: "valueRenderOption", In: "query", Type: "string", Default: "UNFORMATTED_VALUE"},
					Param{Name: "dateTimeRenderOption", In: "query", Type: "string", Default: "FORMATTED_STRING"},
					Param{Name: "returnObjects", In: "option", Type: "boolean", Default: false},
				)},
				"getValues": {Method: "GET", Path: "/{{.spreadsheetId}}/values/{{.range}}", ResponseMap: "values", Params: append(sheetRangeParams(),
					Param{Name: "valueRenderOption", In: "query", Type: "string", Default: "UNFORMATTED_VALUE"},
					Param{Name: "dateTimeRenderOption", In: "query", Type: "string", Default: "FORMATTED_STRING"},
					Param{Name: "returnObjects", In: "option", Type: "boolean", Default: false},
				)},
				"append": {Method: "POST", Path: "/{{.spreadsheetId}}/values/{{.range}}:append", BodyType: "json", Params: append(sheetRangeParams(),
					Param{Name: "valueInputOption", In: "query", Type: "string", Default: "USER_ENTERED"},
					Param{Name: "insertDataOption", In: "query", Type: "string", Default: "INSERT_ROWS"},
					Param{Name: "values", In: "body", Type: "json"},
					Param{Name: "data", In: "body", Type: "json"},
					Param{Name: "objects", In: "body", Type: "json"},
					Param{Name: "headerOrder", In: "option", Type: "json"},
				)},
				"appendValues": {Method: "POST", Path: "/{{.spreadsheetId}}/values/{{.range}}:append", BodyType: "json", Params: append(sheetRangeParams(),
					Param{Name: "valueInputOption", In: "query", Type: "string", Default: "USER_ENTERED"},
					Param{Name: "insertDataOption", In: "query", Type: "string", Default: "INSERT_ROWS"},
					Param{Name: "values", In: "body", Type: "json"},
					Param{Name: "data", In: "body", Type: "json"},
					Param{Name: "objects", In: "body", Type: "json"},
					Param{Name: "headerOrder", In: "option", Type: "json"},
				)},
				"update": {Method: "PUT", Path: "/{{.spreadsheetId}}/values/{{.range}}", BodyType: "json", Params: append(sheetRangeParams(),
					Param{Name: "valueInputOption", In: "query", Type: "string", Default: "USER_ENTERED"},
					Param{Name: "values", In: "body", Type: "json"},
					Param{Name: "data", In: "body", Type: "json"},
					Param{Name: "objects", In: "body", Type: "json"},
					Param{Name: "headerOrder", In: "option", Type: "json"},
				)},
				"clear": {Method: "POST", Path: "/{{.spreadsheetId}}/values/{{.range}}:clear", Params: sheetRangeParams()},
				"batchRead": {Method: "GET", Path: "/{{.spreadsheetId}}/values:batchGet", ResponseMap: "valueRanges", Params: []Param{
					{Name: "spreadsheetId", In: "path", Required: true, Type: "string"},
					{Name: "ranges", In: "query", Required: true, Type: "string"},
					{Name: "valueRenderOption", In: "query", Type: "string", Default: "UNFORMATTED_VALUE"},
					{Name: "dateTimeRenderOption", In: "query", Type: "string", Default: "FORMATTED_STRING"},
				}},
				"getMetadata": {Method: "GET", Path: "/{{.spreadsheetId}}", Params: []Param{
					{Name: "spreadsheetId", In: "path", Required: true, Type: "string"},
					{Name: "includeGridData", In: "query", Type: "boolean", Default: false},
				}},
				"createSpreadsheet": {Method: "POST", Path: "", BodyType: "json", Params: []Param{
					{Name: "properties", In: "body", Required: true, Type: "json"},
					{Name: "sheets", In: "body", Type: "json"},
				}},
				"batchUpdate": {Method: "POST", Path: "/{{.spreadsheetId}}:batchUpdate", BodyType: "json", Params: []Param{
					{Name: "spreadsheetId", In: "path", Required: true, Type: "string"},
					{Name: "requests", In: "body", Required: true, Type: "json"},
				}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.notion",
			Name:           "notion",
			DisplayName:    "Notion",
			Version:        2,
			Description:    "Interact with Notion pages, databases and blocks",
			BaseURL:        "https://api.notion.com/v1",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "apiKey", "tokenPrefix": "Bearer"},
			CredentialType: "notionApi",
			Category:       "Productivity",
			DefaultHeaders: map[string]string{"Notion-Version": "2022-06-28", "Content-Type": "application/json"},
			Operations: map[string]Operation{
				"default": {Method: "GET", Path: "/users/me"},
				"getPage": {Method: "GET", Path: "/pages/{{.pageId}}", Params: []Param{
					{Name: "pageId", In: "path", Required: true, Type: "string"},
				}},
				"createPage": {Method: "POST", Path: "/pages", BodyType: "json", Params: []Param{
					{Name: "parent", In: "body", Required: true, Type: "json"},
					{Name: "properties", In: "body", Required: true, Type: "json"},
					{Name: "children", In: "body", Type: "json"},
					{Name: "icon", In: "body", Type: "json"},
					{Name: "cover", In: "body", Type: "json"},
				}},
				"updatePage": {Method: "PATCH", Path: "/pages/{{.pageId}}", BodyType: "json", Params: []Param{
					{Name: "pageId", In: "path", Required: true, Type: "string"},
					{Name: "properties", In: "body", Type: "json"},
					{Name: "archived", In: "body", Type: "boolean"},
					{Name: "icon", In: "body", Type: "json"},
				}},
				"archivePage": {Method: "PATCH", Path: "/pages/{{.pageId}}", BodyType: "json", Params: []Param{
					{Name: "pageId", In: "path", Required: true, Type: "string"},
					{Name: "archived", In: "body", Type: "boolean", Default: true},
				}},
				"retrieveDatabase": {Method: "GET", Path: "/databases/{databaseId}", Params: []Param{
					{Name: "databaseId", In: "path", Required: true, Type: "string"},
				}},
				"getDatabase": {Method: "GET", Path: "/databases/{{.databaseId}}", Params: []Param{
					{Name: "databaseId", In: "path", Required: true, Type: "string"},
				}},
				"queryDatabase": {Method: "POST", Path: "/databases/{{.databaseId}}/query", BodyType: "json", ResponseMap: "results", Pagination: &Pagination{Type: "cursor", CursorParam: "start_cursor", NextPagePath: "next_cursor", DataPath: "results", DefaultLimit: 100, LimitParam: "page_size"}, Params: []Param{
					{Name: "databaseId", In: "path", Required: true, Type: "string"},
					{Name: "filter", In: "body", Type: "json"},
					{Name: "sorts", In: "body", Type: "json"},
					{Name: "start_cursor", In: "body", Type: "string"},
					{Name: "page_size", In: "body", Type: "number"},
				}},
				"createDatabase": {Method: "POST", Path: "/databases", BodyType: "json", Params: []Param{
					{Name: "parent", In: "body", Required: true, Type: "json"},
					{Name: "title", In: "body", Required: true, Type: "json"},
					{Name: "properties", In: "body", Required: true, Type: "json"},
				}},
				"search": {Method: "POST", Path: "/search", BodyType: "json", ResponseMap: "results", Params: []Param{
					{Name: "query", In: "body", Type: "string"},
					{Name: "filter", In: "body", Type: "json"},
					{Name: "sort", In: "body", Type: "json"},
				}},
				"getBlockChildren": {Method: "GET", Path: "/blocks/{{.blockId}}/children", ResponseMap: "results", Pagination: &Pagination{Type: "cursor", CursorParam: "start_cursor", NextPagePath: "next_cursor", DataPath: "results", DefaultLimit: 100, LimitParam: "page_size"}, Params: []Param{
					{Name: "blockId", In: "path", Required: true, Type: "string"},
					{Name: "start_cursor", In: "query", Type: "string"},
					{Name: "page_size", In: "query", Type: "number"},
				}},
				"appendBlockChildren": {Method: "PATCH", Path: "/blocks/{{.blockId}}/children", BodyType: "json", ResponseMap: "results", Params: []Param{
					{Name: "blockId", In: "path", Required: true, Type: "string"},
					{Name: "children", In: "body", Required: true, Type: "json"},
				}},
				"deleteBlock": {Method: "DELETE", Path: "/blocks/{{.blockId}}", Params: []Param{
					{Name: "blockId", In: "path", Required: true, Type: "string"},
				}},
				"listUsers": {Method: "GET", Path: "/users", ResponseMap: "results", Pagination: &Pagination{Type: "cursor", CursorParam: "start_cursor", NextPagePath: "next_cursor", DataPath: "results", DefaultLimit: 100, LimitParam: "page_size"}, Params: []Param{
					{Name: "start_cursor", In: "query", Type: "string"},
					{Name: "page_size", In: "query", Type: "number"},
				}},
				"getUser": {Method: "GET", Path: "/users/{{.userId}}", Params: []Param{
					{Name: "userId", In: "path", Required: true, Type: "string"},
				}},
				"getMe": {Method: "GET", Path: "/users/me"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.airtable",
			Name:           "airtable",
			DisplayName:    "Airtable",
			Version:        2,
			Description:    "Read and write records in Airtable bases",
			BaseURL:        "https://api.airtable.com/v0",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "apiKey", "tokenPrefix": "Bearer"},
			CredentialType: "airtableApi",
			Category:       "Data & Storage",
			DefaultHeaders: map[string]string{"Content-Type": "application/json"},
			Operations: map[string]Operation{
				"default": {Method: "GET", Path: "/meta/bases", ResponseMap: "bases", Pagination: &Pagination{Type: "cursor", CursorParam: "offset", NextPagePath: "offset", DataPath: "bases", DefaultLimit: 100, LimitParam: "pageSize"}, Params: []Param{
					{Name: "offset", In: "query", Type: "string"},
					{Name: "pageSize", In: "query", Type: "number"},
				}},
				"list": {Method: "GET", Path: "/{{.baseId}}/{{.tableId}}", ResponseMap: "records", Pagination: &Pagination{Type: "cursor", CursorParam: "offset", NextPagePath: "offset", DataPath: "records", DefaultLimit: 100, LimitParam: "pageSize"}, Params: append(airtableTableParams(),
					Param{Name: "filterByFormula", In: "query", Type: "string"},
					Param{Name: "sort", In: "query", Type: "json"},
					Param{Name: "view", In: "query", Type: "string"},
					Param{Name: "fields", In: "query", Type: "json"},
					Param{Name: "maxRecords", In: "query", Type: "number"},
					Param{Name: "cellFormat", In: "query", Type: "string", Default: "json"},
					Param{Name: "timeZone", In: "query", Type: "string"},
					Param{Name: "offset", In: "query", Type: "string"},
					Param{Name: "pageSize", In: "query", Type: "number"},
				)},
				"listRecords": {Method: "GET", Path: "/{baseId}/{tableIdOrName}", ResponseMap: "records", Pagination: &Pagination{Type: "cursor", CursorParam: "offset", NextPagePath: "offset", DataPath: "records", DefaultLimit: 100, LimitParam: "pageSize"}, Params: append(airtableCompatTableParams(),
					Param{Name: "filterByFormula", In: "query", Type: "string"},
					Param{Name: "sort", In: "query", Type: "json"},
					Param{Name: "view", In: "query", Type: "string"},
					Param{Name: "fields", In: "query", Type: "json"},
					Param{Name: "offset", In: "query", Type: "string"},
					Param{Name: "pageSize", In: "query", Type: "number"},
				)},
				"get":       {Method: "GET", Path: "/{{.baseId}}/{{.tableId}}/{{.recordId}}", Params: append(airtableTableParams(), Param{Name: "recordId", In: "path", Required: true, Type: "string"})},
				"getRecord": {Method: "GET", Path: "/{baseId}/{tableIdOrName}/{recordId}", Params: append(airtableCompatTableParams(), Param{Name: "recordId", In: "path", Required: true, Type: "string"})},
				"create": {Method: "POST", Path: "/{{.baseId}}/{{.tableId}}", BodyType: "json", Params: append(airtableTableParams(),
					Param{Name: "records", In: "body", Required: true, Type: "json"},
					Param{Name: "typecast", In: "body", Type: "boolean", Default: false},
				)},
				"createRecord": {Method: "POST", Path: "/{baseId}/{tableIdOrName}", BodyType: "json", Params: append(airtableCompatTableParams(),
					Param{Name: "records", In: "body", Required: true, Type: "json"},
					Param{Name: "typecast", In: "body", Type: "boolean", Default: false},
				)},
				"update": {Method: "PATCH", Path: "/{{.baseId}}/{{.tableId}}", BodyType: "json", Params: append(airtableTableParams(),
					Param{Name: "records", In: "body", Required: true, Type: "json"},
					Param{Name: "typecast", In: "body", Type: "boolean", Default: false},
				)},
				"updateRecord":   {Method: "PATCH", Path: "/{baseId}/{tableIdOrName}/{recordId}", BodyType: "json", Params: append(airtableCompatTableParams(), Param{Name: "recordId", In: "path", Required: true, Type: "string"}, Param{Name: "fields", In: "body", Required: true, Type: "json"})},
				"replace":        {Method: "PUT", Path: "/{{.baseId}}/{{.tableId}}", BodyType: "json", Params: append(airtableTableParams(), Param{Name: "records", In: "body", Required: true, Type: "json"})},
				"delete":         {Method: "DELETE", Path: "/{{.baseId}}/{{.tableId}}/{{.recordId}}", Params: append(airtableTableParams(), Param{Name: "recordId", In: "path", Required: true, Type: "string"})},
				"deleteRecord":   {Method: "DELETE", Path: "/{baseId}/{tableIdOrName}/{recordId}", Params: append(airtableCompatTableParams(), Param{Name: "recordId", In: "path", Required: true, Type: "string"})},
				"deleteMultiple": {Method: "DELETE", Path: "/{{.baseId}}/{{.tableId}}", Params: append(airtableTableParams(), Param{Name: "records", In: "query", Required: true, Type: "json"})},
				"listBases": {Method: "GET", Path: "/meta/bases", ResponseMap: "bases", Pagination: &Pagination{Type: "cursor", CursorParam: "offset", NextPagePath: "offset", DataPath: "bases", DefaultLimit: 100, LimitParam: "pageSize"}, Params: []Param{
					{Name: "offset", In: "query", Type: "string"},
					{Name: "pageSize", In: "query", Type: "number"},
				}},
				"getBaseSchema": {Method: "GET", Path: "/meta/bases/{{.baseId}}/tables", ResponseMap: "tables", Params: []Param{{Name: "baseId", In: "path", Required: true, Type: "string"}}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.jira",
			Name:           "jira",
			DisplayName:    "Jira",
			Version:        1,
			Description:    "Manage Jira Cloud issues, projects and transitions",
			BaseURL:        "https://{{.domain}}/rest/api/3",
			AuthType:       "basic",
			AuthConfig:     map[string]string{"usernameField": "email", "passwordField": "apiToken"},
			CredentialType: "jiraSoftwareCloudApi",
			Category:       "Project Management",
			DefaultHeaders: map[string]string{"Accept": "application/json", "Content-Type": "application/json"},
			Operations: map[string]Operation{
				"default": {Method: "GET", Path: "/myself"},
				"getIssue": {Method: "GET", Path: "/issue/{{.issueKey}}", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "fields", In: "query", Type: "string"},
					{Name: "expand", In: "query", Type: "string"},
				}},
				"createIssue": {Method: "POST", Path: "/issue", BodyType: "json", Params: []Param{
					{Name: "fields", In: "body", Required: true, Type: "json"},
					{Name: "update", In: "body", Type: "json"},
				}},
				"updateIssue": {Method: "PUT", Path: "/issue/{{.issueKey}}", BodyType: "json", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "fields", In: "body", Type: "json"},
					{Name: "update", In: "body", Type: "json"},
				}},
				"deleteIssue": {Method: "DELETE", Path: "/issue/{{.issueKey}}", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "deleteSubtasks", In: "query", Type: "string", Default: "true"},
				}},
				"searchIssues": {Method: "POST", Path: "/issue/search", BodyType: "json", ResponseMap: "issues", Pagination: &Pagination{Type: "offset", OffsetParam: "startAt", LimitParam: "maxResults", DataPath: "issues", DefaultLimit: 50, MaxItems: 10000}, Params: []Param{
					{Name: "jql", In: "body", Required: true, Type: "string"},
					{Name: "fields", In: "body", Type: "json", Default: []any{"summary", "status", "assignee", "priority", "issuetype", "created", "updated"}},
					{Name: "fieldsByKeys", In: "body", Type: "boolean", Default: false},
					{Name: "expand", In: "body", Type: "json"},
					{Name: "startAt", In: "body", Type: "number"},
					{Name: "maxResults", In: "body", Type: "number"},
				}},
				"getTransitions": {Method: "GET", Path: "/issue/{{.issueKey}}/transitions", ResponseMap: "transitions", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
				}},
				"transitionIssue": {Method: "POST", Path: "/issue/{{.issueKey}}/transitions", BodyType: "json", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "transition", In: "body", Required: true, Type: "json"},
					{Name: "fields", In: "body", Type: "json"},
					{Name: "comment", In: "body", Type: "string"},
				}},
				"addComment": {Method: "POST", Path: "/issue/{{.issueKey}}/comment", BodyType: "json", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "body", In: "body", Required: true, Type: "json"},
				}},
				"listComments": {Method: "GET", Path: "/issue/{{.issueKey}}/comment", ResponseMap: "comments", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "orderBy", In: "query", Type: "string", Default: "-created"},
				}},
				"listProjects": {Method: "GET", Path: "/project/search", ResponseMap: "values", Pagination: &Pagination{Type: "offset", OffsetParam: "startAt", LimitParam: "maxResults", DataPath: "values", DefaultLimit: 50}, Params: []Param{
					{Name: "query", In: "query", Type: "string"},
					{Name: "orderBy", In: "query", Type: "string", Default: "name"},
					{Name: "typeKey", In: "query", Type: "string"},
					{Name: "startAt", In: "query", Type: "number"},
					{Name: "maxResults", In: "query", Type: "number"},
				}},
				"getProject": {Method: "GET", Path: "/project/{{.projectKey}}", Params: []Param{
					{Name: "projectKey", In: "path", Required: true, Type: "string"},
				}},
				"searchUsers": {Method: "GET", Path: "/user/search", Params: []Param{
					{Name: "query", In: "query", Required: true, Type: "string"},
					{Name: "maxResults", In: "query", Type: "number", Default: 50},
				}},
				"addWorklog": {Method: "POST", Path: "/issue/{{.issueKey}}/worklog", BodyType: "json", Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "timeSpent", In: "body", Required: true, Type: "string"},
					{Name: "started", In: "body", Type: "string"},
					{Name: "comment", In: "body", Type: "json"},
				}},
				"addAttachment": {Method: "POST", Path: "/issue/{{.issueKey}}/attachments", BodyType: "multipart", Headers: map[string]string{"X-Atlassian-Token": "no-check"}, Params: []Param{
					{Name: "issueKey", In: "path", Required: true, Type: "string"},
					{Name: "file", In: "body", Required: true, Type: "binary"},
				}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.hubspot",
			Name:           "hubspot",
			DisplayName:    "HubSpot",
			Version:        2,
			Description:    "Manage HubSpot CRM contacts, companies, deals and properties",
			BaseURL:        "https://api.hubapi.com",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bearer"},
			CredentialType: "hubspotPrivateAppApi",
			Category:       "Marketing & CRM",
			DefaultHeaders: map[string]string{"Content-Type": "application/json"},
			Operations: map[string]Operation{
				"default":      {Method: "GET", Path: "/crm/v3/objects/contacts", ResponseMap: "results", Pagination: hubspotCursorPagination(), Params: hubspotListParams()},
				"listContacts": {Method: "GET", Path: "/crm/v3/objects/contacts", ResponseMap: "results", Pagination: hubspotCursorPagination(), Params: hubspotListParams()},
				"getContact": {Method: "GET", Path: "/crm/v3/objects/contacts/{{.contactId}}", Params: []Param{
					{Name: "contactId", In: "path", Required: true, Type: "string"},
					{Name: "properties", In: "query", Type: "string"},
					{Name: "associations", In: "query", Type: "string"},
				}},
				"createContact": {Method: "POST", Path: "/crm/v3/objects/contacts", BodyType: "json", Params: []Param{
					{Name: "properties", In: "body", Required: true, Type: "json"},
					{Name: "associations", In: "body", Type: "json"},
				}},
				"updateContact": {Method: "PATCH", Path: "/crm/v3/objects/contacts/{{.contactId}}", BodyType: "json", Params: []Param{
					{Name: "contactId", In: "path", Required: true, Type: "string"},
					{Name: "properties", In: "body", Required: true, Type: "json"},
				}},
				"deleteContact": {Method: "DELETE", Path: "/crm/v3/objects/contacts/{{.contactId}}", Params: []Param{{Name: "contactId", In: "path", Required: true, Type: "string"}}},
				"searchContacts": {Method: "POST", Path: "/crm/v3/objects/contacts/search", BodyType: "json", ResponseMap: "results", Pagination: &Pagination{Type: "cursor", CursorParam: "after", NextPagePath: "paging.next.after", DataPath: "results", DefaultLimit: 100, LimitParam: "limit"}, Params: []Param{
					{Name: "filterGroups", In: "body", Type: "json"},
					{Name: "sorts", In: "body", Type: "json"},
					{Name: "properties", In: "body", Type: "json", Default: []any{"firstname", "lastname", "email", "phone"}},
					{Name: "limit", In: "body", Type: "number", Default: 100},
					{Name: "after", In: "body", Type: "string"},
				}},
				"batchCreateContacts": {Method: "POST", Path: "/crm/v3/objects/contacts/batch/create", BodyType: "json", ResponseMap: "results", Params: []Param{{Name: "inputs", In: "body", Required: true, Type: "json"}}},
				"batchUpdateContacts": {Method: "POST", Path: "/crm/v3/objects/contacts/batch/update", BodyType: "json", ResponseMap: "results", Params: []Param{{Name: "inputs", In: "body", Required: true, Type: "json"}}},
				"getCompany": {Method: "GET", Path: "/crm/v3/objects/companies/{{.companyId}}", Params: []Param{
					{Name: "companyId", In: "path", Required: true, Type: "string"},
					{Name: "properties", In: "query", Type: "string", Default: "name,domain,industry,city,country,phone,numberofemployees"},
				}},
				"createCompany": {Method: "POST", Path: "/crm/v3/objects/companies", BodyType: "json", Params: []Param{{Name: "properties", In: "body", Required: true, Type: "json"}}},
				"getDeal": {Method: "GET", Path: "/crm/v3/objects/deals/{{.dealId}}", Params: []Param{
					{Name: "dealId", In: "path", Required: true, Type: "string"},
					{Name: "properties", In: "query", Type: "string", Default: "dealname,amount,dealstage,pipeline,closedate,hubspot_owner_id"},
				}},
				"createDeal": {Method: "POST", Path: "/crm/v3/objects/deals", BodyType: "json", Params: []Param{{Name: "properties", In: "body", Required: true, Type: "json"}}},
				"listDeals":  {Method: "GET", Path: "/crm/v3/objects/deals", ResponseMap: "results", Pagination: hubspotCursorPagination(), Params: hubspotListParams()},
				"searchDeals": {Method: "POST", Path: "/crm/v3/objects/deals/search", BodyType: "json", ResponseMap: "results", Pagination: &Pagination{Type: "cursor", CursorParam: "after", NextPagePath: "paging.next.after", DataPath: "results", DefaultLimit: 100, LimitParam: "limit"}, Params: []Param{
					{Name: "filterGroups", In: "body", Type: "json"},
					{Name: "sorts", In: "body", Type: "json"},
					{Name: "properties", In: "body", Type: "json", Default: []any{"dealname", "amount", "dealstage", "pipeline"}},
					{Name: "limit", In: "body", Type: "number", Default: 100},
					{Name: "after", In: "body", Type: "string"},
				}},
				"searchCompanies": {Method: "POST", Path: "/crm/v3/objects/companies/search", BodyType: "json", ResponseMap: "results", Pagination: &Pagination{Type: "cursor", CursorParam: "after", NextPagePath: "paging.next.after", DataPath: "results", DefaultLimit: 100, LimitParam: "limit"}, Params: []Param{
					{Name: "filterGroups", In: "body", Type: "json"},
					{Name: "sorts", In: "body", Type: "json"},
					{Name: "properties", In: "body", Type: "json", Default: []any{"name", "domain", "industry", "city"}},
					{Name: "limit", In: "body", Type: "number", Default: 100},
					{Name: "after", In: "body", Type: "string"},
				}},
				"listProperties": {Method: "GET", Path: "/crm/v3/properties/{{.objectType}}", ResponseMap: "results", Params: []Param{
					{Name: "objectType", In: "path", Required: true, Type: "string"},
					{Name: "archived", In: "query", Type: "boolean", Default: false},
				}},
				"createAssociation": {Method: "PUT", Path: "/crm/v3/objects/{{.fromObjectType}}/{{.fromObjectId}}/associations/{{.toObjectType}}/{{.toObjectId}}/{{.associationType}}", Params: []Param{
					{Name: "fromObjectType", In: "path", Required: true, Type: "string"},
					{Name: "fromObjectId", In: "path", Required: true, Type: "string"},
					{Name: "toObjectType", In: "path", Required: true, Type: "string"},
					{Name: "toObjectId", In: "path", Required: true, Type: "string"},
					{Name: "associationType", In: "path", Required: true, Type: "string"},
				}},
				"getTicket": {Method: "GET", Path: "/crm/v3/objects/tickets/{{.ticketId}}", Params: []Param{
					{Name: "ticketId", In: "path", Required: true, Type: "string"},
					{Name: "properties", In: "query", Type: "string", Default: "subject,hs_pipeline_stage,hs_ticket_priority,hs_ticket_category,createdate"},
				}},
				"createTicket": {Method: "POST", Path: "/crm/v3/objects/tickets", BodyType: "json", Params: []Param{{Name: "properties", In: "body", Required: true, Type: "json"}}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.stripe",
			Name:           "stripe",
			DisplayName:    "Stripe",
			Version:        1,
			Description:    "Process payments and manage customers, subscriptions and invoices with Stripe",
			BaseURL:        "https://api.stripe.com/v1",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "secretKey", "tokenPrefix": "Bearer"},
			CredentialType: "stripeApi",
			Category:       "Finance",
			DefaultHeaders: map[string]string{"Content-Type": "application/x-www-form-urlencoded", "Stripe-Version": "2023-10-16"},
			Operations: map[string]Operation{
				"default":       {Method: "GET", Path: "/account"},
				"getCustomer":   {Method: "GET", Path: "/customers/{{.customerId}}", Params: []Param{{Name: "customerId", In: "path", Required: true, Type: "string"}}},
				"listCustomers": {Method: "GET", Path: "/customers", ResponseMap: "data", Pagination: stripeListPagination(), Params: stripeListParams(Param{Name: "email", In: "query", Type: "string"}, Param{Name: "created[gte]", In: "query", Type: "number"}, Param{Name: "created[lte]", In: "query", Type: "number"})},
				"createCustomer": {Method: "POST", Path: "/customers", BodyType: "form", Params: []Param{
					{Name: "Idempotency-Key", In: "header", Type: "string"},
					{Name: "email", In: "body", Type: "string"},
					{Name: "name", In: "body", Type: "string"},
					{Name: "phone", In: "body", Type: "string"},
					{Name: "description", In: "body", Type: "string"},
					{Name: "metadata[orderId]", In: "body", Type: "string"},
					{Name: "address[line1]", In: "body", Type: "string"},
					{Name: "address[city]", In: "body", Type: "string"},
					{Name: "address[country]", In: "body", Type: "string"},
				}},
				"updateCustomer": {Method: "POST", Path: "/customers/{{.customerId}}", BodyType: "form", Params: []Param{
					{Name: "Idempotency-Key", In: "header", Type: "string"},
					{Name: "customerId", In: "path", Required: true, Type: "string"},
					{Name: "email", In: "body", Type: "string"},
					{Name: "name", In: "body", Type: "string"},
					{Name: "phone", In: "body", Type: "string"},
					{Name: "description", In: "body", Type: "string"},
				}},
				"deleteCustomer": {Method: "DELETE", Path: "/customers/{{.customerId}}", Params: []Param{{Name: "customerId", In: "path", Required: true, Type: "string"}}},
				"createPaymentIntent": {Method: "POST", Path: "/payment_intents", BodyType: "form", Params: []Param{
					{Name: "Idempotency-Key", In: "header", Type: "string"},
					{Name: "amount", In: "body", Required: true, Type: "number"},
					{Name: "currency", In: "body", Required: true, Type: "string", Default: "ron"},
					{Name: "customer", In: "body", Type: "string"},
					{Name: "description", In: "body", Type: "string"},
					{Name: "receipt_email", In: "body", Type: "string"},
					{Name: "payment_method_types[]", In: "body", Type: "string", Default: "card"},
					{Name: "metadata[orderId]", In: "body", Type: "string"},
					{Name: "automatic_payment_methods[enabled]", In: "body", Type: "boolean"},
				}},
				"listPaymentIntents":   {Method: "GET", Path: "/payment_intents", ResponseMap: "data", Pagination: stripeListPagination(), Params: stripeListParams(Param{Name: "customer", In: "query", Type: "string"})},
				"getPaymentIntent":     {Method: "GET", Path: "/payment_intents/{{.paymentIntentId}}", Params: []Param{{Name: "paymentIntentId", In: "path", Required: true, Type: "string"}}},
				"capturePaymentIntent": {Method: "POST", Path: "/payment_intents/{{.paymentIntentId}}/capture", BodyType: "form", Params: []Param{{Name: "paymentIntentId", In: "path", Required: true, Type: "string"}, {Name: "amount_to_capture", In: "body", Type: "number"}}},
				"createRefund":         {Method: "POST", Path: "/refunds", BodyType: "form", Params: []Param{{Name: "Idempotency-Key", In: "header", Type: "string"}, {Name: "payment_intent", In: "body", Type: "string"}, {Name: "charge", In: "body", Type: "string"}, {Name: "amount", In: "body", Type: "number"}, {Name: "reason", In: "body", Type: "string"}}},
				"listCharges":          {Method: "GET", Path: "/charges", ResponseMap: "data", Pagination: stripeListPagination(), Params: stripeListParams(Param{Name: "customer", In: "query", Type: "string"}, Param{Name: "payment_intent", In: "query", Type: "string"})},
				"createSubscription":   {Method: "POST", Path: "/subscriptions", BodyType: "form", Params: []Param{{Name: "Idempotency-Key", In: "header", Type: "string"}, {Name: "customer", In: "body", Required: true, Type: "string"}, {Name: "items[0][price]", In: "body", Required: true, Type: "string"}, {Name: "trial_period_days", In: "body", Type: "number"}, {Name: "payment_behavior", In: "body", Type: "string", Default: "default_incomplete"}, {Name: "collection_method", In: "body", Type: "string"}}},
				"cancelSubscription":   {Method: "DELETE", Path: "/subscriptions/{{.subscriptionId}}", Params: []Param{{Name: "subscriptionId", In: "path", Required: true, Type: "string"}, {Name: "prorate", In: "query", Type: "boolean"}}},
				"listProducts":         {Method: "GET", Path: "/products", ResponseMap: "data", Pagination: stripeListPagination(), Params: stripeListParams(Param{Name: "active", In: "query", Type: "boolean"})},
				"createPrice":          {Method: "POST", Path: "/prices", BodyType: "form", Params: []Param{{Name: "Idempotency-Key", In: "header", Type: "string"}, {Name: "product", In: "body", Required: true, Type: "string"}, {Name: "unit_amount", In: "body", Required: true, Type: "number"}, {Name: "currency", In: "body", Required: true, Type: "string", Default: "ron"}, {Name: "recurring[interval]", In: "body", Type: "string"}, {Name: "nickname", In: "body", Type: "string"}}},
				"createInvoice":        {Method: "POST", Path: "/invoices", BodyType: "form", Params: []Param{{Name: "Idempotency-Key", In: "header", Type: "string"}, {Name: "customer", In: "body", Required: true, Type: "string"}, {Name: "collection_method", In: "body", Type: "string"}, {Name: "days_until_due", In: "body", Type: "number"}, {Name: "description", In: "body", Type: "string"}, {Name: "auto_advance", In: "body", Type: "boolean", Default: true}}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.openAi",
			Name:           "openai",
			DisplayName:    "OpenAI",
			Version:        1,
			Description:    "Use OpenAI models for chat, responses, embeddings, images and audio transcription",
			BaseURL:        "https://api.openai.com/v1",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "apiKey", "tokenPrefix": "Bearer"},
			CredentialType: "openAiApi",
			Category:       "AI",
			DefaultHeaders: map[string]string{"Content-Type": "application/json"},
			Operations: map[string]Operation{
				"default":    {Method: "GET", Path: "/models", ResponseMap: "data"},
				"listModels": {Method: "GET", Path: "/models", ResponseMap: "data"},
				"chatCompletion": {Method: "POST", Path: "/chat/completions", BodyType: "json", Params: []Param{
					{Name: "model", In: "body", Required: true, Type: "string", Default: "gpt-4o-mini"},
					{Name: "messages", In: "body", Required: true, Type: "json"},
					{Name: "temperature", In: "body", Type: "number", Default: 0.7},
					{Name: "max_tokens", In: "body", Type: "number"},
					{Name: "top_p", In: "body", Type: "number", Default: 1},
					{Name: "frequency_penalty", In: "body", Type: "number", Default: 0},
					{Name: "presence_penalty", In: "body", Type: "number", Default: 0},
					{Name: "stream", In: "body", Type: "boolean", Default: false},
					{Name: "tools", In: "body", Type: "json"},
					{Name: "tool_choice", In: "body", Type: "json"},
					{Name: "response_format", In: "body", Type: "json"},
					{Name: "seed", In: "body", Type: "number"},
				}},
				"createChatCompletion": {Method: "POST", Path: "/chat/completions", BodyType: "json", Params: []Param{
					{Name: "model", In: "body", Required: true, Type: "string", Default: "gpt-4o-mini"},
					{Name: "messages", In: "body", Required: true, Type: "json"},
					{Name: "temperature", In: "body", Type: "number", Default: 0.7},
					{Name: "stream", In: "body", Type: "boolean", Default: false},
				}},
				"createResponse": {Method: "POST", Path: "/responses", BodyType: "json", Params: []Param{
					{Name: "model", In: "body", Required: true, Type: "string", Default: "gpt-4o-mini"},
					{Name: "input", In: "body", Required: true, Type: "json"},
					{Name: "instructions", In: "body", Type: "string"},
					{Name: "temperature", In: "body", Type: "number"},
					{Name: "max_output_tokens", In: "body", Type: "number"},
					{Name: "tools", In: "body", Type: "json"},
				}},
				"embedding": {Method: "POST", Path: "/embeddings", BodyType: "json", ResponseMap: "data", Params: []Param{
					{Name: "model", In: "body", Required: true, Type: "string", Default: "text-embedding-3-small"},
					{Name: "input", In: "body", Required: true, Type: "json"},
					{Name: "encoding_format", In: "body", Type: "string", Default: "float"},
					{Name: "dimensions", In: "body", Type: "number"},
				}},
				"createEmbedding": {Method: "POST", Path: "/embeddings", BodyType: "json", ResponseMap: "data", Params: []Param{
					{Name: "model", In: "body", Required: true, Type: "string", Default: "text-embedding-3-small"},
					{Name: "input", In: "body", Required: true, Type: "json"},
					{Name: "encoding_format", In: "body", Type: "string", Default: "float"},
				}},
				"imageGeneration": {Method: "POST", Path: "/images/generations", BodyType: "json", ResponseMap: "data", Params: []Param{
					{Name: "model", In: "body", Type: "string", Default: "dall-e-3"},
					{Name: "prompt", In: "body", Required: true, Type: "string"},
					{Name: "n", In: "body", Type: "number", Default: 1},
					{Name: "size", In: "body", Type: "string", Default: "1024x1024"},
					{Name: "quality", In: "body", Type: "string", Default: "standard"},
					{Name: "style", In: "body", Type: "string", Default: "vivid"},
					{Name: "response_format", In: "body", Type: "string", Default: "url"},
				}},
				"audioTranscription": {Method: "POST", Path: "/audio/transcriptions", BodyType: "multipart", Params: []Param{
					{Name: "file", In: "body", Required: true, Type: "binary"},
					{Name: "model", In: "body", Required: true, Type: "string", Default: "whisper-1"},
					{Name: "language", In: "body", Type: "string"},
					{Name: "prompt", In: "body", Type: "string"},
					{Name: "response_format", In: "body", Type: "string", Default: "json"},
					{Name: "temperature", In: "body", Type: "number"},
				}},
				"audioTranslation": {Method: "POST", Path: "/audio/translations", BodyType: "multipart", Params: []Param{
					{Name: "file", In: "body", Required: true, Type: "binary"},
					{Name: "model", In: "body", Required: true, Type: "string", Default: "whisper-1"},
					{Name: "response_format", In: "body", Type: "string", Default: "json"},
					{Name: "temperature", In: "body", Type: "number"},
				}},
				"moderate": {Method: "POST", Path: "/moderations", BodyType: "json", Params: []Param{
					{Name: "input", In: "body", Required: true, Type: "string"},
					{Name: "model", In: "body", Type: "string", Default: "text-moderation-latest"},
				}},
			},
		},
		{
			NodeType:       "n8n-nodes-base.telegram",
			Name:           "telegram",
			DisplayName:    "Telegram",
			Version:        1,
			Description:    "Telegram Bot API messaging, chat, webhook and update operations",
			BaseURL:        "https://api.telegram.org",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bot"},
			CredentialType: "telegramApi",
			Category:       "Communication",
			Operations: map[string]Operation{
				"default":     {Method: "GET", Path: "/bot{accessToken}/getMe"},
				"sendMessage": {Method: "POST", Path: "/bot{accessToken}/sendMessage"},
				"sendPhoto":   {Method: "POST", Path: "/bot{accessToken}/sendPhoto"},
				"getUpdates":  {Method: "GET", Path: "/bot{accessToken}/getUpdates"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.discord",
			Name:           "discord",
			DisplayName:    "Discord",
			Version:        2,
			Description:    "Discord bot messages, channels, guilds, members, reactions and webhooks",
			BaseURL:        "https://discord.com/api/v10",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "botToken", "tokenPrefix": "Bot"},
			CredentialType: "discordBotApi",
			Category:       "Communication",
			Operations: map[string]Operation{
				"default":      {Method: "GET", Path: "/users/@me"},
				"getChannel":   {Method: "GET", Path: "/channels/{channelId}"},
				"sendMessage":  {Method: "POST", Path: "/channels/{channelId}/messages"},
				"createThread": {Method: "POST", Path: "/channels/{channelId}/threads"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.twilio",
			Name:           "twilio",
			DisplayName:    "Twilio",
			Version:        1,
			Description:    "Twilio SMS, MMS, calls, lookup and verify operations",
			BaseURL:        "https://api.twilio.com/2010-04-01",
			AuthType:       "basic",
			AuthConfig:     map[string]string{"usernameField": "accountSid", "passwordField": "authToken"},
			CredentialType: "twilioApi",
			Category:       "Communication",
			Operations: map[string]Operation{
				"default":      {Method: "GET", Path: "/Accounts/{accountSid}.json"},
				"sendSms":      {Method: "POST", Path: "/Accounts/{accountSid}/Messages.json"},
				"listMessages": {Method: "GET", Path: "/Accounts/{accountSid}/Messages.json"},
				"getMessage":   {Method: "GET", Path: "/Accounts/{accountSid}/Messages/{messageSid}.json"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.sendGrid",
			Name:           "sendGrid",
			DisplayName:    "SendGrid",
			Version:        1,
			Description:    "SendGrid email delivery, marketing contacts, lists and suppressions",
			BaseURL:        "https://api.sendgrid.com/v3",
			AuthType:       "bearer",
			AuthConfig:     map[string]string{"tokenField": "apiKey", "tokenPrefix": "Bearer"},
			CredentialType: "sendGridApi",
			Category:       "Communication",
			Operations: map[string]Operation{
				"default":  {Method: "GET", Path: "/user/account"},
				"sendMail": {Method: "POST", Path: "/mail/send"},
				"getStats": {Method: "GET", Path: "/stats"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.shopify",
			Name:           "shopify",
			DisplayName:    "Shopify",
			Version:        1,
			Description:    "Shopify Admin API orders, products, customers, inventory and webhooks",
			BaseURL:        "https://{shopSubdomain}.myshopify.com/admin/api/2024-10",
			AuthType:       "header",
			AuthConfig:     map[string]string{"headerName": "X-Shopify-Access-Token", "tokenField": "accessToken"},
			CredentialType: "shopifyAccessTokenApi",
			Category:       "Sales",
			Operations: map[string]Operation{
				"default":       {Method: "GET", Path: "/shop.json"},
				"listProducts":  {Method: "GET", Path: "/products.json"},
				"getProduct":    {Method: "GET", Path: "/products/{productId}.json"},
				"createProduct": {Method: "POST", Path: "/products.json"},
				"listOrders":    {Method: "GET", Path: "/orders.json"},
				"getOrder":      {Method: "GET", Path: "/orders/{orderId}.json"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.microsoftTeams",
			Name:           "microsoftTeams",
			DisplayName:    "Microsoft Teams",
			Version:        1,
			Description:    "Microsoft Teams and Graph API messages, teams, channels, users and chats",
			BaseURL:        "https://graph.microsoft.com/v1.0",
			AuthType:       "oauth2",
			AuthConfig:     map[string]string{"tokenField": "accessToken", "tokenPrefix": "Bearer", "tokenURL": "https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token", "grantType": "authorizationCode"},
			CredentialType: "microsoftTeamsOAuth2Api",
			Category:       "Communication",
			Operations: map[string]Operation{
				"default":            {Method: "GET", Path: "/me"},
				"sendChannelMessage": {Method: "POST", Path: "/teams/{teamId}/channels/{channelId}/messages"},
				"listTeams":          {Method: "GET", Path: "/me/joinedTeams"},
				"listChannels":       {Method: "GET", Path: "/teams/{teamId}/channels"},
			},
		},
		{
			NodeType:       "n8n-nodes-base.trello",
			Name:           "trello",
			DisplayName:    "Trello",
			Version:        1,
			Description:    "Trello boards, lists, cards, checklists, labels, comments and attachments",
			BaseURL:        "https://api.trello.com/1",
			AuthType:       "query",
			AuthConfig:     map[string]string{"keyField": "apiKey", "tokenField": "token"},
			CredentialType: "trelloApi",
			Category:       "Productivity",
			Operations: map[string]Operation{
				"default":    {Method: "GET", Path: "/members/me"},
				"listBoards": {Method: "GET", Path: "/members/me/boards"},
				"listCards":  {Method: "GET", Path: "/lists/{listId}/cards"},
				"createCard": {Method: "POST", Path: "/cards"},
				"updateCard": {Method: "PUT", Path: "/cards/{cardId}"},
			},
		},
	}
}
